id: AAE4F012C
base_file: fE99A.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - nl
  - bo
  datatype: PlainText
  created_at: 2022-05-30 23:05:32.787282
  last_modified_at: 2022-05-30 23:05:32.787285
