id: AAE4F012C
base_file: fB474.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 23:05:32.779978
  last_modified_at: 2022-05-30 23:05:32.779986
