id: AAE4F012C
base_file: fD41D.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - it
  - nl
  - bo
  datatype: PlainText
  created_at: 2022-05-30 23:05:32.784772
  last_modified_at: 2022-05-30 23:05:32.784791
