id: AAE4F012C
base_file: fA70A.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 23:05:32.777692
  last_modified_at: 2022-05-30 23:05:32.777717
