id: AAE4F012C
base_file: f0D13.txt
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-30 23:05:32.774101
  last_modified_at: 2022-05-30 23:05:32.774110
